### ISSUE TITLE
Is the date and time a local time or UTC

### ISSUE THREAD

**Issue by huitang-earth** [Between-the-Fjords/funcab_data#36]
@audhalbritter 

When I tried to match the date and time of the observation with model, I need to know whether they represent the same date and time. The model usually use UTC time. I notice that most of the data files have a date and time format like such "2015-07-09T14:28:30Z". I understood that the suffix "Z" should denote UTC time (https://en.wikipedia.org/wiki/ISO_8601#Local_time_(unqualified)). So, am I right that you are using UTC time for all the data file?

**Comment by audhalbritter** [comment]
FunCaB datasets have UTC + 2 timezone. VCG datasets are different.
