### ISSUE TITLE
the unit of soil moisture data is ambiguous

### ISSUE THREAD

**Issue by huitang-earth** [Between-the-Fjords/funcab_data#37]
In the documentation, the unit of soil moisture is m3/m3. 

But in the data file (i.e., "FunCaB_clean_soilMoisture_2015-2019.csv"), soil moisture data seem to have a unit of m3/m3/100 (percentage of m3/m3). I have to divide 100 to get a reasonable value of soil moisture in m3/m3 to compare with the model results. 

Could this be clearer in the documentation?

**Comment by audhalbritter** [comment]
Yes, that is correct. We will improve the documentation of this in the final data paper version.
