### ISSUE TITLE
the unit of "gpp" in "FunCaB_clean_Cflux_2015-2017.csv"

### ISSUE THREAD

**Issue by huitang-earth** [Between-the-Fjords/funcab_data#38]
In the documentation, the unit of "gpp" is said to be:  µmol mol-1 s-1 CO2.

But the model use: gC/m2/s

How to convert the unit from the one used by observation to that used by model?

It seems that the unit of gpp from observation misses "per square meter".

**Comment by audhalbritter** [comment]
Right, the fluxes should includes area. I'll have to check with Inge if that is the plot or if it was scaled to square meter, which would make more sense.

**Comment by huitang-earth** [comment]
@audhalbritter I have emailed Inge about the unit. Here is her reply in case you have not contacted her. 

########################
Regarding the units, the unit in the documentation seems to be wrong. It should be micromol/m2/s. For the conversion to gC/m2/s see following post
https://onlineconversion.vbulletin.net/forum/main-forums/convert-and-calculate/8797-convert-soil-respiration-rates-in-umol-co2-m-2-s-1-to-g-co2-m-2-h-1
########################

**Comment by audhalbritter** [comment]
Thank you Hui for checking with Inge. We'll fix the issue with the unit in the final version of the datapaper.
