### ISSUE TITLE
moss height data and missing values?

### ISSUE THREAD

**Issue by huitang-earth** [Between-the-Fjords/funcab_data#40]
This is just a clarifying issue.

I noticed that moss height is measure only in 2017, but not 2015. Is this the case?

In addition, BOR3 site have only 3 blocks Arh4, Arh2 and Arh3 in 2017 for GF treatment, but in 2015, there are 4 blocks (Arh1GF, Arh2GF, Arh3GF, Arh4GF) for GF treatment. I noticed that Arh2GF have 2 values in 2017. I am confused why Arh2GF have two entries in 2017, and suspect that one of Arh2GF might be Arh1GF?  See the following figure:

![Screenshot from 2022-03-29 08-10-21](https://user-images.githubusercontent.com/17548269/160538125-9ae71fc0-02f3-4db1-a5e0-e7528e268d08.png)

**Comment by audhalbritter** [comment]
@huitang-earth Which data file did you use for extracting the moss height?
Moss height was measured each year and it is in this dataset on the FunCaB repo: FunCaB_clean_composition_2015-2019.csv

**Comment by huitang-earth** [comment]
@audhalbritter yes, I use this file. But I do not find moss height available in 2015 for at least BOR3 (Arh) site.

**Comment by audhalbritter** [comment]
Ok good. There is something funny with this community file. There are much more observations in 2015 than in the other years and I don't understand why.

Moss hight might be missing in some of the plots. I'm trying to figure out where it was lost or if it never was recorded.

I think you are right with the Arh2GF being Arh1GF.

**Comment by audhalbritter** [comment]
I fixed the plotID issue as you suggested. Moss height should be measured in all the plots each year. If it is missing, then it must have been forgotten. It might be possible to impute the value from previous and following years. Note that in 2016 only control plots were recorded.
