### ISSUE TITLE
subplots in community data

### ISSUE THREAD

**Issue by evalieungh** [Between-the-Fjords/funcab_data#44]
Hei! 

When recording the community data, am I correct that you used 25x25cm plots with 25 subplots kind of like this:

| 1 |2|3|4|5|
|---|---|---|---|---|
|6|7|8|9|10|
|11|12|13|14|15|
|16|17|18|19|20|
|21|22|23|24|25|

In the raw data files (on OSF under 3_Plant_composition/FunCaB_raw_community_2015-2019.zip/raw/funcab_Gudmedalen.xlsx), there is community data from subplots indexed 1-5. Which subplots are those, following the diagram above? @joatop said it was probably the middle one (13) plus four more... But which ones? 
An what is subPlot = T ?

**Comment by audhalbritter** [comment]
Hei,
Presence was only recorded in 5 subplots, according to your grid it is 8, 12, 13, 14, and 18. So, the cross in the middle. The datapaper describes this and has a figure showing it. I am not sure what version of the data you are using, but the clean data does not have subplot. We only provide cover for each plot, not subplots. I don't know what subplot T is. You can check the cleaning code, maybe it gives some indication what it means.

**Comment by evalieungh** [comment]
Thanks, @audhalbritter ! 
The subplot data is only in the raw data, as far as I tan tell, so it should be used with caution. I'll probably end up not using it after all, but it's nice to know it is there. We are working on a model with subplot-level presence/absence, and I thought the FunCaB subplot data could be useful as an independent validation data set (which is rare and very nice to have). Turns out our model is too simple for it to be worth the hassle of more data cleaning, but it might be used next time...
